from pathlib import Path

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "cache"
MODEL_DIR = BASE_DIR / "saved_models"
SIGNAL_LOG = BASE_DIR / "signal_history.jsonl"
LOG_DIR = BASE_DIR / "logs"

TICKER = "^IXIC"
HISTORY_START = "1985-01-02"

TRAIN_YEARS = 5
TEST_YEARS = 1
STEP_MONTHS = 6
FINAL_HOLDOUT_DAYS = 30

FORWARD_DAYS = 5
BUY_THRESH = 0.015
SELL_THRESH = -0.015

LSTM_WINDOW = 60
LSTM_HIDDEN = 128
LSTM_LAYERS = 2
LSTM_DROPOUT = 0.2
LSTM_EPOCHS = 50
LSTM_BATCH = 32
LSTM_LR = 1e-3

RF_N_ESTIMATORS = 500
RF_MAX_DEPTH = 8
RF_MIN_SAMPLES = 50

XGB_N_ESTIMATORS = 300
XGB_MAX_DEPTH = 5
XGB_LR = 0.05

DEFAULT_CAPITAL = 100_000.0
MIN_CONFIDENCE = 0.55
KELLY_MAX_FRAC = 0.25
ATR_RISK_DOLLARS = 1_000.0
